# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unit/myf/ais3p-reporter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unit/myf/ais3p-reporter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unit/myf/ais3p-reporter/CMakeFiles /home/unit/myf/ais3p-reporter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unit/myf/ais3p-reporter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/unit/myf/ais3p-reporter/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ais3p-reporter

# Build rule for target.
ais3p-reporter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ais3p-reporter
.PHONY : ais3p-reporter

# fast build rule for target.
ais3p-reporter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/build
.PHONY : ais3p-reporter/fast

src/App/App.o: src/App/App.cpp.o
.PHONY : src/App/App.o

# target to build an object file
src/App/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/App.cpp.o
.PHONY : src/App/App.cpp.o

src/App/App.i: src/App/App.cpp.i
.PHONY : src/App/App.i

# target to preprocess a source file
src/App/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/App.cpp.i
.PHONY : src/App/App.cpp.i

src/App/App.s: src/App/App.cpp.s
.PHONY : src/App/App.s

# target to generate assembly for a file
src/App/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/App.cpp.s
.PHONY : src/App/App.cpp.s

src/App/Data/Binary/Meta.o: src/App/Data/Binary/Meta.cpp.o
.PHONY : src/App/Data/Binary/Meta.o

# target to build an object file
src/App/Data/Binary/Meta.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/Data/Binary/Meta.cpp.o
.PHONY : src/App/Data/Binary/Meta.cpp.o

src/App/Data/Binary/Meta.i: src/App/Data/Binary/Meta.cpp.i
.PHONY : src/App/Data/Binary/Meta.i

# target to preprocess a source file
src/App/Data/Binary/Meta.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/Data/Binary/Meta.cpp.i
.PHONY : src/App/Data/Binary/Meta.cpp.i

src/App/Data/Binary/Meta.s: src/App/Data/Binary/Meta.cpp.s
.PHONY : src/App/Data/Binary/Meta.s

# target to generate assembly for a file
src/App/Data/Binary/Meta.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/Data/Binary/Meta.cpp.s
.PHONY : src/App/Data/Binary/Meta.cpp.s

src/App/Data/Config/Config.o: src/App/Data/Config/Config.cpp.o
.PHONY : src/App/Data/Config/Config.o

# target to build an object file
src/App/Data/Config/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/Data/Config/Config.cpp.o
.PHONY : src/App/Data/Config/Config.cpp.o

src/App/Data/Config/Config.i: src/App/Data/Config/Config.cpp.i
.PHONY : src/App/Data/Config/Config.i

# target to preprocess a source file
src/App/Data/Config/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/Data/Config/Config.cpp.i
.PHONY : src/App/Data/Config/Config.cpp.i

src/App/Data/Config/Config.s: src/App/Data/Config/Config.cpp.s
.PHONY : src/App/Data/Config/Config.s

# target to generate assembly for a file
src/App/Data/Config/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/App/Data/Config/Config.cpp.s
.PHONY : src/App/Data/Config/Config.cpp.s

src/Error/Error.o: src/Error/Error.cpp.o
.PHONY : src/Error/Error.o

# target to build an object file
src/Error/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/Error/Error.cpp.o
.PHONY : src/Error/Error.cpp.o

src/Error/Error.i: src/Error/Error.cpp.i
.PHONY : src/Error/Error.i

# target to preprocess a source file
src/Error/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/Error/Error.cpp.i
.PHONY : src/Error/Error.cpp.i

src/Error/Error.s: src/Error/Error.cpp.s
.PHONY : src/Error/Error.s

# target to generate assembly for a file
src/Error/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/Error/Error.cpp.s
.PHONY : src/Error/Error.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ais3p-reporter.dir/build.make CMakeFiles/ais3p-reporter.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ais3p-reporter"
	@echo "... src/App/App.o"
	@echo "... src/App/App.i"
	@echo "... src/App/App.s"
	@echo "... src/App/Data/Binary/Meta.o"
	@echo "... src/App/Data/Binary/Meta.i"
	@echo "... src/App/Data/Binary/Meta.s"
	@echo "... src/App/Data/Config/Config.o"
	@echo "... src/App/Data/Config/Config.i"
	@echo "... src/App/Data/Config/Config.s"
	@echo "... src/Error/Error.o"
	@echo "... src/Error/Error.i"
	@echo "... src/Error/Error.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/unit/myf/ais3p-reporter/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

